"""create appointment table

Revision ID: 6ec1b9ca7c2f
Revises: 34fd9db1f25f
Create Date: 2025-06-30 23:30:01.887560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ec1b9ca7c2f'
down_revision: Union[str, None] = '34fd9db1f25f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predictions', sa.Column('image_filename', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('predictions', 'image_filename')
    # ### end Alembic commands ###
